# Generated by Django 3.2 on 2023-03-15 16:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text_eng',
            field=models.TextField(default=django.utils.timezone.now, help_text='Enter the text', verbose_name='Text post on eng'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='title_eng',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Title post on eng'),
            preserve_default=False,
        ),
    ]
